download_url: https://galaxy.ansible.com/download/f5networks-f5_modules-1.18.0.tar.gz
format_version: 1.0.0
name: f5_modules
namespace: f5networks
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.18.0
version_url: https://galaxy.ansible.com/api/v2/collections/f5networks/f5_modules/versions/1.18.0/
